variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: TestProject
  value: '**/*UnitTests.csproj'
- name: BuildParameters.Project
  value: '**/HexIO.csproj'

name: v$(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: "Restore Solution"
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      projects: $(BuildParameters.solution)
  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: "Run Unit Tests"
    inputs:
      command: 'test'
      projects: $(TestProject)
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testRunner: VSTest
      testResultsFiles: '**\*.trx'
  - task: DotNetCoreCLI@2
    displayName: "Pack Project"
    inputs:
      command: 'pack'
      packagesToPack: $(BuildParameters.Project)
      versioningScheme: byEnvVar
      versionEnvVar: PackageVersion
  - task: GitHubRelease@1
    displayName: "Publish Relase To GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(Build.BuildNumber)'
      title: '$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'